/* The following code was generated by JFlex 1.7.0 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Scanner.flex</tt>
 */
public class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\47\1\12\1\13\1\13\1\12\22\0\1\47\1\15\1\43"+
    "\1\10\1\0\1\22\1\17\1\45\2\46\1\11\1\21\1\46\1\4"+
    "\1\5\1\22\12\1\2\46\1\16\1\14\1\16\2\0\4\2\1\6"+
    "\25\2\1\46\1\44\1\46\1\0\1\3\1\0\1\25\1\41\1\36"+
    "\1\37\1\7\1\27\1\3\1\32\1\30\1\3\1\42\1\33\1\3"+
    "\1\31\1\34\1\35\1\3\1\26\1\23\1\24\1\40\5\3\1\46"+
    "\1\20\1\46\7\0\1\13\u1fa2\0\1\13\1\13\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\1\1\4\1\5"+
    "\1\6\1\7\1\10\2\1\2\4\14\1\1\11\1\0"+
    "\1\3\1\12\1\6\1\0\1\5\1\0\1\4\1\10"+
    "\1\7\1\13\15\0\1\14\3\0\1\15\1\3\15\0"+
    "\1\16\1\15\1\0\1\3\1\17\1\5\1\0\1\20"+
    "\7\0\2\15\1\0\1\3\5\0\1\15\1\3\2\0"+
    "\1\15\1\3\1\15\30\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0168\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208"+
    "\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0348"+
    "\0\u0370\0\u0398\0\u03c0\0\u03e8\0\50\0\u0410\0\u0438\0\50"+
    "\0\50\0\u0460\0\u0488\0\u04b0\0\50\0\50\0\50\0\50"+
    "\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05c8\0\u05f0"+
    "\0\u0618\0\u0640\0\u0668\0\u0690\0\u03c0\0\50\0\u06b8\0\u06e0"+
    "\0\u0708\0\u0730\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820"+
    "\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0910\0\u0938\0\u0960"+
    "\0\50\0\u0988\0\u09b0\0\u09d8\0\50\0\50\0\u0a00\0\50"+
    "\0\u0a28\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18\0\u0b40"+
    "\0\u0b68\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08\0\u0c30\0\u0c58"+
    "\0\u0c80\0\u0ca8\0\u0cd0\0\u0cf8\0\u0d20\0\u0d48\0\u0d70\0\u0d98"+
    "\0\u0dc0\0\u0de8\0\u0e10\0\u0e38\0\u0e60\0\u0e88\0\u0eb0\0\u0ed8"+
    "\0\u0f00\0\u0f28\0\u0f50\0\u0f78\0\u0fa0\0\u0fc8\0\u0ff0\0\u1018"+
    "\0\u1040\0\u1068\0\u1090\0\u10b8\0\u10e0\0\u1108\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\2\1\4\1\6"+
    "\1\7\1\10\1\11\1\0\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\2\1\23\1\24"+
    "\1\25\2\2\1\26\1\27\1\2\1\30\1\31\1\2"+
    "\1\32\1\2\1\33\1\2\1\34\1\35\1\11\51\0"+
    "\1\3\3\0\1\36\43\0\1\37\1\0\1\37\3\0"+
    "\1\37\13\0\20\37\6\0\1\3\2\0\1\40\7\0"+
    "\1\41\66\0\1\42\24\0\1\43\1\44\47\0\1\45"+
    "\2\0\1\41\45\0\1\11\34\0\1\11\14\0\1\46"+
    "\52\0\1\47\50\0\1\47\30\0\1\3\12\0\1\41"+
    "\4\0\1\50\42\0\1\41\57\0\1\51\51\0\1\52"+
    "\30\0\1\53\65\0\1\54\2\0\1\55\7\0\1\56"+
    "\40\0\1\57\52\0\1\60\53\0\1\61\43\0\1\62"+
    "\22\0\1\63\66\0\1\64\21\0\43\65\1\66\1\67"+
    "\3\65\44\70\1\71\1\0\2\70\1\0\1\72\47\0"+
    "\1\73\1\0\1\73\3\0\1\73\13\0\20\73\30\0"+
    "\1\74\24\0\12\43\2\0\34\43\11\44\1\75\36\44"+
    "\25\0\1\76\62\0\1\77\33\0\1\100\56\0\1\101"+
    "\45\0\1\102\47\0\1\103\53\0\1\104\46\0\1\105"+
    "\37\0\1\57\54\0\1\106\54\0\1\107\20\0\1\110"+
    "\64\0\1\65\1\0\1\65\2\0\1\65\11\0\2\65"+
    "\50\0\1\111\26\0\1\70\1\0\1\70\2\0\1\70"+
    "\12\0\2\70\3\0\1\112\4\0\2\113\41\0\1\114"+
    "\1\0\1\114\3\0\1\114\13\0\20\114\14\0\1\115"+
    "\40\0\10\44\1\116\1\75\36\44\26\0\1\117\30\0"+
    "\1\120\100\0\1\121\32\0\1\77\54\0\1\122\55\0"+
    "\1\123\51\0\1\117\44\0\1\115\36\0\1\124\12\0"+
    "\1\125\43\0\1\126\41\0\1\127\23\0\1\130\4\0"+
    "\2\113\41\0\1\131\2\0\1\132\14\0\1\132\27\0"+
    "\1\133\1\0\1\133\3\0\1\133\13\0\20\133\31\0"+
    "\1\115\51\0\1\134\44\0\1\135\50\0\1\136\53\0"+
    "\1\137\47\0\1\123\44\0\1\140\64\0\1\115\6\0"+
    "\1\141\4\0\2\113\41\0\1\131\47\0\1\142\1\0"+
    "\1\142\3\0\1\142\13\0\20\142\36\0\1\115\50\0"+
    "\1\115\45\0\1\143\50\0\1\144\44\0\1\74\22\0"+
    "\1\145\4\0\2\113\41\0\1\146\1\0\1\146\3\0"+
    "\1\146\13\0\20\146\41\0\1\134\53\0\1\74\10\0"+
    "\1\147\4\0\2\113\41\0\1\150\1\0\1\150\3\0"+
    "\1\150\13\0\20\150\13\0\2\113\41\0\1\151\1\0"+
    "\1\151\3\0\1\151\13\0\20\151\6\0\1\152\1\0"+
    "\1\152\3\0\1\152\13\0\20\152\6\0\1\153\1\0"+
    "\1\153\3\0\1\153\13\0\20\153\6\0\1\154\1\0"+
    "\1\154\3\0\1\154\13\0\20\154\6\0\1\155\1\0"+
    "\1\155\3\0\1\155\13\0\20\155\6\0\1\156\1\0"+
    "\1\156\3\0\1\156\13\0\20\156\6\0\1\157\1\0"+
    "\1\157\3\0\1\157\13\0\20\157\6\0\1\160\1\0"+
    "\1\160\3\0\1\160\13\0\20\160\6\0\1\161\1\0"+
    "\1\161\3\0\1\161\13\0\20\161\6\0\1\162\1\0"+
    "\1\162\3\0\1\162\13\0\20\162\6\0\1\163\1\0"+
    "\1\163\3\0\1\163\13\0\20\163\6\0\1\164\1\0"+
    "\1\164\3\0\1\164\13\0\20\164\6\0\1\165\1\0"+
    "\1\165\3\0\1\165\13\0\20\165\6\0\1\166\1\0"+
    "\1\166\3\0\1\166\13\0\20\166\6\0\1\167\1\0"+
    "\1\167\3\0\1\167\13\0\20\167\6\0\1\170\1\0"+
    "\1\170\3\0\1\170\13\0\20\170\6\0\1\171\1\0"+
    "\1\171\3\0\1\171\13\0\20\171\6\0\1\172\1\0"+
    "\1\172\3\0\1\172\13\0\20\172\6\0\1\173\1\0"+
    "\1\173\3\0\1\173\13\0\20\173\6\0\1\174\1\0"+
    "\1\174\3\0\1\174\13\0\20\174\6\0\1\175\1\0"+
    "\1\175\3\0\1\175\13\0\20\175\6\0\1\176\1\0"+
    "\1\176\3\0\1\176\13\0\20\176\6\0\1\177\1\0"+
    "\1\177\3\0\1\177\13\0\20\177\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4400];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\32\1\1\11\1\0\1\1\2\11\1\0"+
    "\1\1\1\0\4\11\15\0\1\11\3\0\2\1\15\0"+
    "\1\11\1\1\1\0\1\1\2\11\1\0\1\11\7\0"+
    "\2\1\1\0\1\1\5\0\2\1\2\0\32\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /* No extra imports needed — Token and TokenType are in the same package */


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Lexical error at Line " + (yyline+1) +
                       ", Col " + (yycolumn+1) +
                       ": unrecognised character '" + yytext() + "'");
            } 
            // fall through
          case 17: break;
          case 2: 
            { return new Token(TokenType.INT_LITERAL, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 18: break;
          case 3: 
            { return new Token(TokenType.IDENTIFIER, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 19: break;
          case 4: 
            { return new Token(TokenType.ARITH_OP,      yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 20: break;
          case 5: 
            { /* discard */
            } 
            // fall through
          case 21: break;
          case 6: 
            { return new Token(TokenType.ASSIGN_OP,     yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 22: break;
          case 7: 
            { return new Token(TokenType.LOGICAL_OP,    yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 23: break;
          case 8: 
            { return new Token(TokenType.RELATIONAL_OP, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 24: break;
          case 9: 
            { return new Token(TokenType.DELIMITER, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 25: break;
          case 10: 
            { return new Token(TokenType.DEC_OP,        yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 26: break;
          case 11: 
            { return new Token(TokenType.INC_OP,        yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 27: break;
          case 12: 
            { return new Token(TokenType.TEXT_LITERAL, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 28: break;
          case 13: 
            { return new Token(TokenType.REAL_LITERAL, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 29: break;
          case 14: 
            { return new Token(TokenType.CHAR_LITERAL, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 30: break;
          case 15: 
            { return new Token(TokenType.KEYWORD, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 31: break;
          case 16: 
            { return new Token(TokenType.BOOL_LITERAL, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
