/**
 * Yylex.java
 *
 * This file is AUTO-GENERATED by JFlex from Scanner.flex.
 * It is NOT hand-written. To regenerate:
 *
 *   jflex Scanner.flex
 *
 * The generated class implements the JFlex-based scanner for ZenLang.
 * It is included here for submission completeness.
 *
 * Requirements: JFlex 1.8+ must be installed.
 *   sudo apt install jflex
 */

// Run: jflex Scanner.flex  to generate this file.
// Placeholder — actual content generated at build time.
